import type { Metadata } from 'next';

import StyledComponentsRegistry from './registry';
import ClientLayout from './ClientLayout';

export const metadata: Metadata = {
  title: 'Mobile Payments',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <StyledComponentsRegistry>
          <ClientLayout>{children}</ClientLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
